name: makers
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  http: ^1.4.0
  get: ^4.7.2
  fl_chart: ^1.0.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  shimmer: ^3.0.0
  shared_preferences: ^2.3.0
  google_fonts: ^6.2.1
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^17.1.2

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.9
  flutter_launcher_icons: ^0.13.1


flutter_native_splash:
  color: "#9B0062"
  image: assets/images/admin.png
  android: true
  ios: true
  android_12:
    image: assets/images/admin.png
    icon_background_color: "#9B0062"
    image_dark: assets/images/admin.png
    icon_background_color_dark: "#9B0062"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/makers.jpg


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - assets/images/
 